### ISSUE TITLE
round functions not exported?

### ISSUE THREAD

**Issue by josephstatwick** [EricArcher/swfscMisc#1]
I'm trying to use the round functions for data frames, but I'm getting the following error:
> swfscMisc::signif()
Error: 'signif' is not an exported object from 'namespace:swfscMisc'

I'm using version 1.2 in R 3.5.1. The functions show up in the package helptext, but not in the predictive list that pops up for swfscMisc::

are they missing the @export tags or am I doing something wrong?

**Comment by EricArcher** [comment]
The problem may be that the function that is exported is actually `swfscMisc::signif.data.frame()`. Try that and let me know if it works.

**Comment by josephstatwick** [comment]
hm...

> swfscMisc::signif.data.frame()
Error: 'signif.data.frame' is not an exported object from 'namespace:swfscMisc'

Still having trouble... 

That said, I'm not sure this is really what I was looking for anyway, since I was looking to format numbers for display/export (specifically for axis labels). This doesn't address the biggest issue with signif(), (and numeric vectors in general) namely, displaying trailing zeros where they're not merited. It seems the only real "fix" is still a call to format() or its derivatives, which coerces numeric columns into character format.

> options(scipen = 999)
> signif.data.frame <- function(x, digits = 6) {
>    for(i in 1:ncol(x)) {
>     if(is.numeric(x[[i]])) x[[i]] <- signif(x[[i]], digits = digits)
>    }
>   x
> }
> signif(c(500,0.55555555559))
[1] 500.000000   0.555556
> signif.data.frame(data.frame("x" = c(500,0.55555555559)))
           x
1 500.000000
2   0.555556
> data.frame("x" = format(signif(c(500,0.55555555559)), drop0trailing = TRUE))
           x
1        500
2   0.555556

**Comment by EricArcher** [comment]
Hmmm.... that is odd. I use @export in the documentation and it shows as an exported S3 function in [NAMESPACE](https://github.com/EricArcher/swfscMisc/blob/master/NAMESPACE). 

I wonder if I have to also export the generic `signif()` in my package for it to be seen as being exported. I'll look into it...

You are right though, it sounds like`format()` is more like what you are looking for than `signif()`

**Comment by EricArcher** [comment]
I think I see what the issue is. The set of functions that I have written `data.frame` methods for (`ceiling()`, `floor()`, `trunc()`, `round()`, and `signif()`) do not have generics defined for them in `base`. Because of that, when I define and export an S3 method, it gets registered in the NAMESPACE for `swfscMisc`, but is not "exported". I would have to also register a generic which would then mask the `base` version of the function. It seems that the intended solution is to explicitly reference it with `swfscMisc:::signif.data.frame()`.

**Comment by josephstatwick** [comment]
Looks like the ::: solution works just fine, thanks. There are definitely other instances for which this would be useful, so I'll definitely keep it in my back pocket. A more seamless integration with the base functions would of course be on my wishlist, but this is perfectly workable for now. Thanks again!
